#!/usr/bin/env python3
"""Extract C and Web translation literals into i18n/central-scrutinizer.pot."""
import json
import re
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "i18n" / "central-scrutinizer.pot"
keys = set()
def decode(value):
    return value.replace("\\\\n", "\n").replace("\\\\t", "\t").replace("\\n", "\n").replace("\\t", "\t")
for path in sorted((ROOT / "src").glob("*.c")):
    text = path.read_text(encoding="utf-8", errors="replace")
    keys.update(decode(value) for value in re.findall(r'CS_T\("((?:[^"\\]|\\.)*)"\)', text))
for path in sorted((ROOT / "web" / "src").rglob("*.tsx")) + sorted((ROOT / "web" / "src").rglob("*.ts")):
    text = path.read_text(encoding="utf-8", errors="replace")
    keys.update(decode(value) for value in re.findall(r'\bt\(\s*["\']([^"\']+)["\']\s*\)', text))
# Preserve keys used indirectly by error/status paths while the Web API
# messages are assembled outside JSX call sites.
tsv = ROOT / "i18n" / "zh_CN.tsv"
for line in tsv.read_text(encoding="utf-8").splitlines():
    if line and not line.startswith("#") and "\t" in line:
        key, _ = line.split("\t", 1)
        keys.add(decode(key))
lines = ['# CentralScrutinizer UI strings. GENERATED by tools/i18n-extract.py',
         'msgid ""', 'msgstr "Content-Type: text/plain; charset=UTF-8\\n"', '']
for key in sorted(keys):
    # json.dumps is not PO escaping: it emits literal newlines differently on
    # some Python versions. Keep every PO entry on one escaped line.
    escaped = key.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t")
    lines += [f'msgid "{escaped}"', 'msgstr ""', '']
parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
fresh = set(keys)
if args.check:
    committed = {m.group(1).replace("\\n", "\n").replace("\\t", "\t").replace('\\"', '"').replace('\\\\', '\\') for m in re.finditer(r'^msgid "((?:[^"\\]|\\.)*)"$', OUT.read_text(encoding="utf-8"), re.M) if m.group(1)} if OUT.exists() else set()
    if fresh != committed:
        raise SystemExit(f"POT is stale: missing={len(fresh - committed)} stale={len(committed - fresh)}")
    print(f"POT current: {len(fresh)} keys")
else:
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"extracted {len(keys)} keys")
